# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2d4d6e24c709421aca3a3a53c288f44fec81d793e6abb60a1d292f6ea30e8b78ad1a8a93a34f2849bc7972584d1274d436581e3b9b0ab3fc76faf9eab1b3eb77

test:
  secret_key_base: f006847cf29fc1ae10f2af45e5f9e39b557a447128eea4f129adbc5d421d20dc0325abe1284b3fc754895b458e698a132fe46b2c263d62b043fd251b9ec69849

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
